/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* RKA */
export const RKA_GET_LIST = "RKA_GET_LIST";
export const RKA_GET_LIST_SUCCESS = "RKA_GET_LIST_SUCCESS";
export const RKA_GET_LIST_ERROR = "RKA_GET_LIST_ERROR";
export const RKA_GET_LIST_WITH_FILTER = "RKA_GET_LIST_WITH_FILTER";
export const RKA_GET_LIST_WITH_ORDER = "RKA_GET_LIST_WITH_ORDER";
export const RKA_GET_LIST_SEARCH = "RKA_GET_LIST_SEARCH";
export const RKA_ADD_ITEM = "RKA_ADD_ITEM";
export const RKA_ADD_ITEM_SUCCESS = "RKA_ADD_ITEM_SUCCESS";
export const RKA_ADD_ITEM_ERROR = "RKA_ADD_ITEM_ERROR";
export const RKA_EDIT_ITEM = "RKA_EDIT_ITEM";
export const RKA_EDIT_ITEM_SUCCESS = "RKA_EDIT_ITEM_SUCCESS";
export const RKA_EDIT_ITEM_ERROR = "RKA_EDIT_ITEM_ERROR";

/* RAB */
export const RAB_GET_LIST = "RAB_GET_LIST";
export const RAB_GET_LIST_SUCCESS = "RAB_GET_LIST_SUCCESS";
export const RAB_GET_LIST_ERROR = "RAB_GET_LIST_ERROR";
export const RAB_GET_LIST_WITH_FILTER = "RAB_GET_LIST_WITH_FILTER";
export const RAB_GET_LIST_WITH_ORDER = "RAB_GET_LIST_WITH_ORDER";
export const RAB_GET_LIST_SEARCH = "RAB_GET_LIST_SEARCH";
export const RAB_ADD_ITEM = "RAB_ADD_ITEM";
export const RAB_ADD_ITEM_SUCCESS = "RAB_ADD_ITEM_SUCCESS";
export const RAB_ADD_ITEM_ERROR = "RAB_ADD_ITEM_ERROR";
export const RAB_EDIT_ITEM = "RAB_EDIT_ITEM";
export const RAB_EDIT_ITEM_SUCCESS = "RAB_EDIT_ITEM_SUCCESS";
export const RAB_EDIT_ITEM_ERROR = "RAB_EDIT_ITEM_ERROR";
export const RAB_PROGRES_GET_LIST = "RAB_PROGRES_GET_LIST";
export const RAB_PROGRES_GET_LIST_SUCCESS = "RAB_PROGRES_GET_LIST_SUCCESS";
export const RAB_PROGRES_GET_LIST_ERROR = "RAB_PROGRES_GET_LIST_ERROR";
export const RAB_SUMMARY_EXPORT = "RAB_SUMMARY_EXPORT";
export const RAB_SUMMARY_EXPORT_SUCCESS = "RAB_SUMMARY_EXPORT_SUCCESS";
export const RAB_SUMMARY_EXPORT_ERROR = "RAB_SUMMARY_EXPORT_ERROR";

/* RPB */
export const RPB_GET_LIST = "RPB_GET_LIST";
export const RPB_GET_LIST_SUCCESS = "RPB_GET_LIST_SUCCESS";
export const RPB_GET_LIST_ERROR = "RPB_GET_LIST_ERROR";
export const RPB_GET_LIST_WITH_FILTER = "RPB_GET_LIST_WITH_FILTER";
export const RPB_GET_LIST_WITH_ORDER = "RPB_GET_LIST_WITH_ORDER";
export const RPB_GET_LIST_SEARCH = "RPB_GET_LIST_SEARCH";
export const RPB_ADD_ITEM = "RPB_ADD_ITEM";
export const RPB_ADD_ITEM_SUCCESS = "RPB_ADD_ITEM_SUCCESS";
export const RPB_ADD_ITEM_ERROR = "RPB_ADD_ITEM_ERROR";
export const RPB_EDIT_ITEM = "RPB_EDIT_ITEM";
export const RPB_EDIT_ITEM_SUCCESS = "RPB_EDIT_ITEM_SUCCESS";
export const RPB_EDIT_ITEM_ERROR = "RPB_EDIT_ITEM_ERROR";

/* PERSEKOT */
export const PERSEKOT_GET_LIST = "PERSEKOT_GET_LIST";
export const PERSEKOT_GET_LIST_SUCCESS = "PERSEKOT_GET_LIST_SUCCESS";
export const PERSEKOT_GET_LIST_ERROR = "PERSEKOT_GET_LIST_ERROR";
export const PERSEKOT_GET_LIST_WITH_FILTER = "PERSEKOT_GET_LIST_WITH_FILTER";
export const PERSEKOT_GET_LIST_WITH_ORDER = "PERSEKOT_GET_LIST_WITH_ORDER";
export const PERSEKOT_GET_LIST_SEARCH = "PERSEKOT_GET_LIST_SEARCH";
export const PERSEKOT_ADD_ITEM = "PERSEKOT_ADD_ITEM";
export const PERSEKOT_ADD_ITEM_SUCCESS = "PERSEKOT_ADD_ITEM_SUCCESS";
export const PERSEKOT_ADD_ITEM_ERROR = "PERSEKOT_ADD_ITEM_ERROR";
export const PERSEKOT_EDIT_ITEM = "PERSEKOT_EDIT_ITEM";
export const PERSEKOT_EDIT_ITEM_SUCCESS = "PERSEKOT_EDIT_ITEM_SUCCESS";
export const PERSEKOT_EDIT_ITEM_ERROR = "PERSEKOT_EDIT_ITEM_ERROR";
export const PERSEKOT_REPORT_ITEM = "PERSEKOT_REPORT_ITEM";
export const PERSEKOT_REPORT_ITEM_SUCCESS = "PERSEKOT_REPORT_ITEM_SUCCESS";
export const PERSEKOT_REPORT_ITEM_ERROR = "PERSEKOT_REPORT_ITEM_ERROR";

/* SPPD */
export const SPPD_GET_LIST = "SPPD_GET_LIST";
export const SPPD_GET_LIST_SUCCESS = "SPPD_GET_LIST_SUCCESS";
export const SPPD_GET_LIST_ERROR = "SPPD_GET_LIST_ERROR";
export const SPPD_GET_LIST_WITH_FILTER = "SPPD_GET_LIST_WITH_FILTER";
export const SPPD_GET_LIST_WITH_ORDER = "SPPD_GET_LIST_WITH_ORDER";
export const SPPD_GET_LIST_SEARCH = "SPPD_GET_LIST_SEARCH";
export const SPPD_ADD_ITEM = "SPPD_ADD_ITEM";
export const SPPD_ADD_ITEM_SUCCESS = "SPPD_ADD_ITEM_SUCCESS";
export const SPPD_ADD_ITEM_ERROR = "SPPD_ADD_ITEM_ERROR";
export const SPPD_EDIT_ITEM = "SPPD_EDIT_ITEM";
export const SPPD_EDIT_ITEM_SUCCESS = "SPPD_EDIT_ITEM_SUCCESS";
export const SPPD_EDIT_ITEM_ERROR = "SPPD_EDIT_ITEM_ERROR";

/* FEE */
export const FEE_GET_LIST = "FEE_GET_LIST";
export const FEE_GET_LIST_SUCCESS = "FEE_GET_LIST_SUCCESS";
export const FEE_GET_LIST_ERROR = "FEE_GET_LIST_ERROR";
export const FEE_GET_LIST_WITH_FILTER = "FEE_GET_LIST_WITH_FILTER";
export const FEE_GET_LIST_WITH_ORDER = "FEE_GET_LIST_WITH_ORDER";
export const FEE_GET_LIST_SEARCH = "FEE_GET_LIST_SEARCH";
export const FEE_ADD_ITEM = "FEE_ADD_ITEM";
export const FEE_ADD_ITEM_SUCCESS = "FEE_ADD_ITEM_SUCCESS";
export const FEE_ADD_ITEM_ERROR = "FEE_ADD_ITEM_ERROR";
export const FEE_EDIT_ITEM = "FEE_EDIT_ITEM";
export const FEE_EDIT_ITEM_SUCCESS = "FEE_EDIT_ITEM_SUCCESS";
export const FEE_EDIT_ITEM_ERROR = "FEE_EDIT_ITEM_ERROR";

/* PENDAPATAN */
export const PENDAPATAN_GET_LIST = "PENDAPATAN_GET_LIST";
export const PENDAPATAN_GET_LIST_SUCCESS = "PENDAPATAN_GET_LIST_SUCCESS";
export const PENDAPATAN_GET_LIST_ERROR = "PENDAPATAN_GET_LIST_ERROR";
export const PENDAPATAN_GET_LIST_WITH_FILTER = "PENDAPATAN_GET_LIST_WITH_FILTER";
export const PENDAPATAN_GET_LIST_WITH_ORDER = "PENDAPATAN_GET_LIST_WITH_ORDER";
export const PENDAPATAN_GET_LIST_SEARCH = "PENDAPATAN_GET_LIST_SEARCH";
export const PENDAPATAN_ADD_ITEM = "PENDAPATAN_ADD_ITEM";
export const PENDAPATAN_ADD_ITEM_SUCCESS = "PENDAPATAN_ADD_ITEM_SUCCESS";
export const PENDAPATAN_ADD_ITEM_ERROR = "PENDAPATAN_ADD_ITEM_ERROR";
export const PENDAPATAN_EDIT_ITEM = "PENDAPATAN_EDIT_ITEM";
export const PENDAPATAN_EDIT_ITEM_SUCCESS = "PENDAPATAN_EDIT_ITEM_SUCCESS";
export const PENDAPATAN_EDIT_ITEM_ERROR = "PENDAPATAN_EDIT_ITEM_ERROR";

/* DASHBOARD */
export const DASHBOARD_GET_PENDING_COUNT = "DASHBOARD_GET_PENDING_COUNT";
export const DASHBOARD_GET_PENDING_COUNT_SUCCESS = "DASHBOARD_GET_PENDING_COUNT_SUCCESS";
export const DASHBOARD_GET_PENDING_COUNT_ERROR = "DASHBOARD_GET_PENDING_COUNT_ERROR";
export const APPROVE_ITEM = "APPROVE_ITEM";
export const APPROVE_ITEM_SUCCESS = "APPROVE_ITEM_SUCCESS";
export const APPROVE_ITEM_ERROR = "APPROVE_ITEM_ERROR";
export const REJECT_ITEM = "REJECT_ITEM";
export const REJECT_ITEM_SUCCESS = "REJECT_ITEM_SUCCESS";
export const REJECT_ITEM_ERROR = "REJECT_ITEM_ERROR";
export const TARGET_ADD_ITEM = "TARGET_ADD_ITEM";
export const TARGET_ADD_ITEM_SUCCESS = "TARGET_ADD_ITEM_SUCCESS";
export const TARGET_ADD_ITEM_ERROR = "TARGET_ADD_ITEM_ERROR";

/* CATEGORY */
export const CATEGORY_GET_LIST = "CATEGORY_GET_LIST";
export const CATEGORY_GET_LIST_SUCCESS = "CATEGORY_GET_LIST_SUCCESS";
export const CATEGORY_GET_LIST_ERROR = "CATEGORY_GET_LIST_ERROR";
export const CATEGORY_ADD_ITEM = "CATEGORY_ADD_ITEM";
export const CATEGORY_ADD_ITEM_SUCCESS = "CATEGORY_ADD_ITEM_SUCCESS";
export const CATEGORY_ADD_ITEM_ERROR = "CATEGORY_ADD_ITEM_ERROR";

/* UPLOAD */
export const UPLOAD_FILES = "UPLOAD_FILES";
export const UPLOAD_FILES_SUCCESS = "UPLOAD_FILES_SUCCESS";
export const UPLOAD_FILES_ERROR = "UPLOAD_FILES_ERROR";
export const GET_FILES = "GET_FILES";
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS";
export const GET_FILES_ERROR = "GET_FILES_ERROR";
export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_ERROR = "DELETE_FILE_ERROR";

/* IMPORT */
export const CSV_IMPORT = "CSV_IMPORT";
export const CSV_IMPORT_SUCCESS = "CSV_IMPORT_SUCCESS";
export const CSV_IMPORT_ERROR = "CSV_IMPORT_ERROR";
export const CSV_GENERATE = "CSV_GENERATE";
export const CSV_GENERATE_SUCCESS = "CSV_GENERATE_SUCCESS";
export const CSV_GENERATE_ERROR = "CSV_GENERATE_ERROR";
export const CSV_ENTRY_GET_TEMPLATE = "CSV_ENTRY_GET_TEMPLATE";
export const CSV_ENTRY_IMPORT = "CSV_ENTRY_IMPORT";
export const CSV_ENTRY_IMPORT_SUCCESS = "CSV_ENTRY_IMPORT_SUCCESS";
export const CSV_ENTRY_IMPORT_ERROR = "CSV_ENTRY_IMPORT_ERROR";
/* CHART */
export const CHART_BY_YEAR_GET = "CHART_BY_YEAR_GET";
export const CHART_BY_YEAR_GET_SUCCESS = "CHART_BY_YEAR_GET_SUCCESS";
export const CHART_BY_YEAR_GET_ERROR = "CHART_BY_YEAR_GET_ERROR";
export const CHART_ON_YEAR_GET = "CHART_ON_YEAR_GET";
export const CHART_ON_YEAR_GET_SUCCESS = "CHART_ON_YEAR_GET_SUCCESS";
export const CHART_ON_YEAR_GET_ERROR = "CHART_ON_YEAR_GET_ERROR";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./rka/actions";
export * from "./rab/actions";
export * from "./rpb/actions";
export * from "./persekot/actions";
export * from "./sppd/actions";
export * from "./fee/actions";
export * from "./pendapatan/actions";
export * from "./dashboard/actions";
export * from "./category/actions";
export * from "./csvImport/actions";
export * from "./chart/actions";
